In [1]:
import sqlalchemy ,pickle
from sqlalchemy import *
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import create_engine

import getpass
myid = getpass.getpass("input DB id : ")
mypw = getpass.getpass("input DB pw : ")
# 유니코드? 특수문자들도 갈 수 있도록 utf8mb4로 설정
SQLALCHEMY_DATABASE_URI = 'mysql://'+myid+':'+mypw+'@13.209.97.247/mrobo?charset=utf8mb4' # 

engine = create_engine(SQLALCHEMY_DATABASE_URI, encoding='utf-8')#,convert_unicode=True)
connectDB = engine.connect()

input DB id : ········
input DB pw : ········

In [2]:
import pandas as pd
# DB에서 불러오기(DataFrame으로 읽기)
#df_info = pd.read_sql_table('auth_user',connectDB) 
df = pd.read_excel("위치")

In [3]:
df

,rcp_no,report,tangible_assets,intangible_assets,total_assets,total_liabilities,capital_stock,capital_surplus,related_earnings,total_capital,...,crp_nm,rcp_dt,crp_cd,date,total_assets.1,total_liabilities.1,total_capital.1,assets_p,capital_p,liabilities_p
0,20180814002954,제20기반기말,3.035662e+10,8.199109e+08,7.050939e+10,1.781889e+10,NaN,1.823045e+10,32021700396,5.269050e+10,...,힘스,20180814,238490,2018-06-01,7.041240e+10,1.906622e+10,5.134618e+10,1.001378,1.026182,0.934579
1,20180515000527,제20기1분기말,3.061589e+10,8.514742e+08,7.041240e+10,1.906622e+10,NaN,1.823045e+10,30690976315,5.134618e+10,...,힘스,20180515,238490,2018-03-01,7.245878e+10,2.026783e+10,5.219094e+10,0.971758,0.983814,0.940713
2,20180330001319,제19기,3.057942e+10,8.698041e+08,7.245878e+10,2.026783e+10,NaN,1.821150e+10,31675574418,5.219094e+10,...,힘스,20180330,238490,2017-12-01,7.395013e+10,1.994374e+10,5.400639e+10,0.979833,0.966385,1.016250
3,20171113000503,제19기3분기말,3.018216e+10,6.773998e+08,7.395013e+10,1.994374e+10,NaN,1.812988e+10,33634130776,5.400639e+10,...,힘스,20171113,238490,2017-09-01,7.395013e+10,1.994374e+10,5.400639e+10,1.000000,1.000000,1.000000
4,20171113000320,제19기3분기말,3.018216e+10,6.773998e+08,7.395013e+10,1.994374e+10,NaN,1.812988e+10,33634130776,5.400639e+10,...,힘스,20171113,238490,2017-09-01,6.206755e+10,3.082003e+10,3.124752e+10,1.191446,1.728341,0.647103
5,20170811000537,제19기반기말,1.748203e+10,6.995046e+08,6.206755e+10,3.082003e+10,2.072000e+09,1.056461e+09,28381867409,3.124752e+10,...,힘스,20170811,238490,2017-06-01,1.346725e+11,8.498929e+10,4.968324e+10,1.000000,1.000000,1.000000
6,20180814001150,제29기반기말,2.170478e+09,4.106928e+09,1.346725e+11,8.498929e+10,6.961238e+09,7.571943e+09,43826988372,4.968324e+10,...,희림,20180814,37440,2018-06-01,1.377429e+11,9.032380e+10,4.741913e+10,0.977709,1.047747,0.940940
7,20180515001170,제29기1분기말,2.170981e+09,4.295059e+09,1.377429e+11,9.032380e+10,6.961238e+09,7.571943e+09,40428347829,4.741913e+10,...,희림,20180515,37440,2018-03-01,1.345528e+11,8.296373e+10,5.158909e+10,1.023709,0.919170,1.088714
8,20180402004201,제28기,2.216054e+09,4.371090e+09,1.345528e+11,8.296373e+10,6.961238e+09,7.571943e+09,44575586995,5.158909e+10,...,희림,20180402,37440,2017-12-01,1.411800e+11,9.128926e+10,4.989070e+10,0.953059,1.034042,0.908801
9,20171114000299,제28기3분기말,2.340957e+09,4.596270e+09,1.411800e+11,9.128926e+10,6.961238e+09,7.571943e+09,42986880310,4.989070e+10,...,희림,20171114,37440,2017-09-01,1.495612e+11,1.005788e+11,4.898247e+10,0.943961,1.018542,0.907639
10,20170814000997,제28기반기말,2.099049e+09,4.824266e+09,1.495612e+11,1.005788e+11,6.961238e+09,7.571943e+09,42052522690,4.898247e+10,...,희림,20170814,37440,2017-06-01,1.377825e+11,8.996352e+10,4.781895e+10,1.085488,1.024332,1.117995
11,20170515002687,제28기1분기말,3.974467e+09,2.861344e+09,1.377825e+11,8.996352e+10,6.961238e+09,7.365277e+09,41068602112,4.781895e+10,...,희림,20170515,37440,2017-03-01,1.434174e+11,9.455628e+10,4.886110e+10,0.960710,0.978671,0.951428
12,20170331003487,제27기,3.330458e+09,2.992487e+09,1.434174e+11,9.455628e+10,6.961238e+09,7.365277e+09,42159240670,4.886110e+10,...,희림,20170331,37440,2016-12-01,1.377076e+11,8.983612e+10,4.787150e+10,1.041463,1.020672,1.052542
13,20161114001040,제27기3분기말,2.536025e+09,2.505346e+09,1.377076e+11,8.983612e+10,6.961238e+09,7.365277e+09,41132394710,4.787150e+10,...,희림,20161114,37440,2016-09-01,1.390055e+11,9.143709e+10,4.756846e+10,0.990663,1.006371,0.982491
14,20160816000952,제27기반기말,1.829474e+09,2.699697e+09,1.390055e+11,9.143709e+10,6.961238e+09,7.365277e+09,40864426398,4.756846e+10,...,희림,20160816,37440,2016-06-01,1.371201e+11,9.013820e+10,4.698195e+10,1.013750,1.012484,1.014410
15,20160516001884,제27기1분기말,1.826330e+09,2.890160e+09,1.371201e+11,9.013820e+10,6.961238e+09,7.365277e+09,40288381923,4.698195e+10,...,희림,20160516,37440,2016-03-01,1.424960e+11,9.467022e+10,4.782581e+10,0.962273,0.982356,0.952128
16,20160330002054,제26기,1.712949e+09,3.254497e+09,1.424960e+11,9.467022e+10,6.961238e+09,7.408035e+09,41296393769,4.782581e+10,...,희림,20160330,37440,2015-12-01,1.420874e+11,9.568330e+10,4.640414e+10,1.002876,1.030637,0.989412
17,20151116000935,제26기3분기말,1.874204e+09,2.925772e+09,1.420874e+11,9.568330e+10,6.961238e+09,7.408035e+09,39879864606,4.640414e+10,...,희림,20151116,37440,2015-09-01,1.382281e+11,9.258996e+10,4.563817e+10,1.027920,1.016783,1.033409
18,20150817000175,제26기반기말,1.980648e+09,3.462954e+09,1.382281e+11,9.258996e+10,6.961238e+09,7.408035e+09,39093481542,4.563817e+10,...,희림,20150817,37440,2015-06-01,1.401358e+11,9.571960e+10,4.441623e+10,0.986387,1.027511,0.967304
19,20150515000759,제26기1분기말,2.173102e+09,3.520182e+09,1.401358e+11,9.571960e+10,6.961238e+09,7.408035e+09,38406927479,4.441623e+10,...,희림,20150515,37440,2015-03-01,1.389441e+11,9.572058e+10,4.322356e+10,1.008577,1.027593,0.999990
20,20150331002240,제25기,7.405919e+09,3.509627e+09,1.389441e+11,9.572058e+10,6.961238e+09,7.605829e+09,37647534650,4.322356e+10,...,희림,20150331,37440,2014-12-01,1.386571e+11,8.578442e+10,5.287270e+10,1.002070,0.817502,1.115827
21,20141120000261,제25기3분기말,7.159305e+09,3.535447e+09,1.386571e+11,8.578442e+10,6.961238e+09,7.605829e+09,47295900184,5.287270e+10,...,희림,20141120,37440,2014-09-01,1.339434e+11,8.205615e+10,5.188723e+10,1.035192,1.018992,1.045436
22,20140829001783,제25기반기말,7.320387e+09,3.592141e+09,1.339434e+11,8.205615e+10,6.961238e+09,7.671167e+09,46558430150,5.188723e+10,...,희림,20140829,37440,2014-06-01,1.354523e+11,8.109345e+10,5.435886e+10,0.988860,0.954531,1.011871
23,20140530001545,제25기1분기말,8.608017e+09,3.371128e+09,1.354523e+11,8.109345e+10,6.961238e+09,7.438545e+09,49296696328,5.435886e+10,...,희림,20140530,37440,2014-03-01,1.292411e+11,7.193714e+10,5.730400e+10,1.048059,0.948605,1.127282
24,20140513002570,제24기,7.680027e+09,3.174387e+09,1.292411e+11,7.193714e+10,6.961238e+09,7.438545e+09,52244735244,5.730400e+10,...,희림,20140513,37440,2013-12-01,1.292411e+11,7.193714e+10,5.730400e+10,1.000000,1.000000,1.000000
25,20140331002289,제24기,7.680027e+09,3.174387e+09,1.292411e+11,7.193714e+10,6.961238e+09,7.438545e+09,52244735244,5.730400e+10,...,희림,20140331,37440,2013-12-01,1.266757e+11,7.161020e+10,5.506552e+10,1.020252,1.040651,1.004566
26,20131128000941,제24기3분기말,7.346109e+09,1.791442e+09,1.266757e+11,7.161020e+10,6.961238e+09,7.438545e+09,49921803141,5.506552e+10,...,희림,20131128,37440,2013-09-01,1.244910e+11,6.720780e+10,5.728318e+10,1.017549,0.961286,1.065504
27,20130829000944,제24기반기말,7.502485e+09,1.847675e+09,1.244910e+11,6.720780e+10,6.961238e+09,7.438545e+09,52136673831,5.728318e+10,...,희림,20130829,37440,2013-06-01,1.376098e+11,8.151972e+10,5.609004e+10,0.904667,1.021272,0.824436
28,20130515000834,제24기1분기말,7.596588e+09,1.908270e+09,1.376098e+11,8.151972e+10,6.961238e+09,7.492115e+09,50998629079,5.609004e+10,...,희림,20130515,37440,2013-03-01,1.275500e+11,7.127401e+10,5.627599e+10,1.078869,0.996696,1.143751
29,20130503000839,제23기,8.024816e+09,1.959993e+09,1.275500e+11,7.127401e+10,6.961238e+09,7.492115e+09,51571412219,5.627599e+10,...,희림,20130503,37440,2012-12-01,1.275500e+11,7.127401e+10,5.627599e+10,1.000000,1.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115744,20071114001274,제18기반기말,8.486781e+09,2.008834e+07,1.620680e+10,8.551096e+09,6.796000e+09,8.547801e+09,7475765384,7.655701e+09,...,3S,20071114,60310,2007-09-01,1.414714e+10,5.834267e+09,8.312874e+09,1.145588,0.920945,1.465667
115745,20070814001569,제18기1분기말,8.496314e+09,1.976550e+07,1.414714e+10,5.834267e+09,6.796000e+09,8.455897e+09,,8.312874e+09,...,3S,20070814,60310,2007-06-01,9.279673e+09,2.098825e+09,7.180848e+09,1.524530,1.157645,2.779778
115746,20070628000329,제17기,4.837931e+09,6.785489e+06,9.279673e+09,2.098825e+09,6.000000e+09,7.430634e+09,,7.180848e+09,...,3S,20070628,60310,2007-03-01,9.496987e+09,3.385211e+09,6.111776e+09,0.977118,1.174920,0.619998
115747,20070214000272,제17기3분기,4.901124e+09,9.104208e+06,9.496987e+09,3.385211e+09,4.300000e+09,6.882439e+09,,6.111776e+09,...,3S,20070214,60310,2006-12-01,1.046199e+10,4.318899e+09,6.143087e+09,0.907761,0.994903,0.783813
115748,20061114001219,제17기반기말,4.955649e+09,7.725912e+06,1.046199e+10,4.318899e+09,4.300000e+09,6.882439e+09,,6.143087e+09,...,3S,20061114,60310,2006-09-01,1.066351e+10,3.993192e+09,6.670314e+09,0.981102,0.920959,1.081565
115749,20060811000447,제17기1분기,4.987674e+09,8.698000e+06,1.066351e+10,3.993192e+09,4.300000e+09,6.882438e+09,,6.670314e+09,...,3S,20060811,60310,2006-06-01,1.038957e+10,3.424763e+09,6.964809e+09,1.026366,0.957717,1.165976
115750,20060719000083,제16기,4.797167e+09,9.335000e+06,1.038957e+10,3.424763e+09,4.300000e+09,6.882438e+09,,6.964809e+09,...,3S,20060719,60310,2006-03-01,1.038957e+10,3.424763e+09,6.964809e+09,1.000000,1.000000,1.000000
115751,20060627000159,제16기,4.797167e+09,9.335000e+06,1.038957e+10,3.424763e+09,4.300000e+09,6.882438e+09,,6.964809e+09,...,3S,20060627,60310,2006-03-01,1.249366e+10,8.327564e+09,4.166099e+09,0.831587,1.671782,0.411256
115752,20060214000101,제16기3분기,4.846941e+09,9.961000e+06,1.249366e+10,8.327564e+09,3.160000e+09,4.649701e+09,,4.166099e+09,...,3S,20060214,60310,2005-12-01,1.013585e+10,5.997106e+09,4.138746e+09,1.232621,1.006609,1.388597
115753,20051114000951,제16기반기말,4.908095e+09,1.058600e+07,1.013585e+10,5.997106e+09,3.160000e+09,4.649701e+09,,4.138746e+09,...,3S,20051114,60310,2005-09-01,1.013585e+10,5.997106e+09,4.138746e+09,1.000000,1.000000,1.000000
115754,20051114000780,제16기반기말,4.908095e+09,1.058600e+07,1.013585e+10,5.997106e+09,3.160000e+09,4.649701e+09,,4.138746e+09,...,3S,20051114,60310,2005-09-01,1.140464e+10,6.979883e+09,4.424759e+09,0.888748,0.935361,0.859199
115755,20050907000221,제16기1분기말,5.159709e+09,1.121100e+07,1.140464e+10,6.979883e+09,3.160000e+09,4.649701e+09,,4.424759e+09,...,3S,20050907,60310,2005-06-01,1.140464e+10,6.979883e+09,4.424759e+09,1.000000,1.000000,1.000000
115756,20050812000616,제16기1분기말,5.159709e+09,1.121100e+07,1.140464e+10,6.979883e+09,3.160000e+09,4.649701e+09,,4.424759e+09,...,3S,20050812,60310,2005-06-01,1.184562e+10,7.482131e+09,4.363489e+09,0.962773,1.014042,0.932874
115757,20050629000340,제15기,5.111029e+09,1.183700e+07,1.184562e+10,7.482131e+09,3.160000e+09,4.649701e+09,,4.363489e+09,...,3S,20050629,60310,2005-03-01,1.161664e+10,7.741491e+09,3.875148e+09,1.019711,1.126019,0.966497
115758,20050214000314,제15분기,4.984301e+09,1.256800e+07,1.161664e+10,7.741491e+09,2.700000e+09,3.916638e+09,-2347700000,3.875148e+09,...,3S,20050214,60310,2004-12-01,1.110528e+10,7.802046e+09,3.303231e+09,1.046047,1.173139,0.992239
115759,20041115000710,제15반기,5.296898e+09,1.330000e+07,1.110528e+10,7.802046e+09,2.000000e+09,3.286639e+09,-1589618000,3.303231e+09,...,3S,20041115,60310,2004-09-01,1.389866e+10,7.939885e+09,5.958775e+09,0.799018,0.554347,0.982640
115760,20040813001209,제15분기,5.041501e+09,1.324000e+07,1.389866e+10,7.939885e+09,2.000000e+09,3.330239e+09,1158454000,5.958775e+09,...,3S,20040813,60310,2004-06-01,1.358411e+10,7.178869e+09,6.405243e+09,1.023156,0.930296,1.106008
115761,20040728000163,제14기,4.654806e+09,9.977000e+06,1.358411e+10,7.178869e+09,2.000000e+09,3.330239e+09,1604922000,6.405243e+09,...,3S,20040728,60310,2004-03-01,1.358411e+10,7.178869e+09,6.405243e+09,1.000000,1.000000,1.000000
115762,20040629000240,제14기,4.654806e+09,9.977000e+06,1.358411e+10,7.178869e+09,2.000000e+09,3.330239e+09,1604922000,6.405243e+09,...,3S,20040629,60310,2004-03-01,1.360138e+10,6.969045e+09,6.632332e+09,0.998731,0.965760,1.030108
115763,20040220000343,제14분기,4.781891e+09,1.048900e+07,1.360138e+10,6.969045e+09,1.200000e+09,4.377715e+09,1584535000,6.632332e+09,...,3S,20040220,60310,2003-12-01,1.360138e+10,6.969045e+09,6.632332e+09,1.000000,1.000000,1.000000
115764,20040213000480,제14분기,4.781891e+09,1.048900e+07,1.360138e+10,6.969045e+09,1.200000e+09,4.377715e+09,1584535000,6.632332e+09,...,3S,20040213,60310,2003-12-01,1.343796e+10,6.731488e+09,6.706476e+09,1.012160,0.988944,1.035290
115765,20031114001057,제14기반기,4.592623e+09,1.100200e+07,1.343796e+10,6.731488e+09,1.200000e+09,4.377715e+09,1619964000,6.706476e+09,...,3S,20031114,60310,2003-09-01,1.283131e+10,6.311664e+09,6.519648e+09,1.047279,1.028656,1.066516
115766,20030926000148,제14기분기,2.642089e+09,9.029000e+06,1.283131e+10,6.311664e+09,1.200000e+09,4.338732e+09,1560759000,6.519648e+09,...,3S,20030926,60310,2003-06-01,1.283131e+10,6.311664e+09,6.519648e+09,1.000000,1.000000,1.000000
115767,20030814000907,제14기분기,2.642089e+09,9.029000e+06,1.283131e+10,6.311664e+09,1.200000e+09,4.338732e+09,1560759000,6.519648e+09,...,3S,20030814,60310,2003-06-01,1.258963e+10,6.232112e+09,6.357521e+09,1.019197,1.025502,1.012765
115768,20040621000108,제13기연간,2.644110e+09,7.636000e+06,1.258963e+10,6.232112e+09,1.200000e+09,4.328945e+09,1549460000,6.357521e+09,...,3S,20040621,60310,2003-03-01,1.258963e+10,6.232112e+09,6.357521e+09,1.000000,1.000000,1.000000
115769,20030630000178,제13기연간,2.644110e+09,7.636000e+06,1.258963e+10,6.232112e+09,1.200000e+09,4.328945e+09,1549460000,6.357521e+09,...,3S,20030630,60310,2003-03-01,1.447044e+10,6.855892e+09,7.614544e+09,0.870024,0.834918,0.909015
115770,20030214000343,제13기분기,2.672861e+09,1.949800e+07,1.447044e+10,6.855892e+09,1.200000e+09,3.467764e+09,1867998000,7.614544e+09,...,3S,20030214,60310,2002-12-01,8.803690e+09,2.337326e+09,6.466364e+09,1.643679,1.177562,2.933220
115771,20021113000428,제13기반기,2.562633e+09,4.943000e+06,8.803690e+09,2.337326e+09,1.200000e+09,3.467764e+09,1772697000,6.466364e+09,...,3S,20021113,60310,2002-09-01,8.847102e+09,2.536548e+09,6.310554e+09,0.995093,1.024690,0.921459
115772,20020814000271,제13기1/4분기,2.518573e+09,2.326890e+08,8.847102e+09,2.536548e+09,1.200000e+09,3.467763e+09,1642791000,6.310554e+09,...,3S,20020814,60310,2002-06-01,6.742684e+09,3.385302e+09,3.357382e+09,1.312104,1.879606,0.749283
115773,20020628000294,제12기,2.102126e+09,5.414000e+06,6.742684e+09,3.385302e+09,8.050000e+08,1.060764e+09,1491618000,3.357382e+09,...,3S,20020628,60310,2002-03-01,NaN,NaN,NaN,1.000000,1.000000,1.000000

In [4]:
df.to_sql(name='DART3_JJW',if_exists='append', con=engine, index=False)

In [26]:
query = " * FROM test_webtoon WHERE averageScore > 9.90"
read_df = pd.read_sql_query(query, connectDB)

ProgrammingError: (_mysql_exceptions.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '* FROM test_webtoon WHERE averageScore > 9.90' at line 1") [SQL: ' * FROM test_webtoon WHERE averageScore > 9.90'] (Background on this error at: http://sqlalche.me/e/f405)